name: Java Ci

on:
  push:
    branches:
        - '**'
  pull_request:
    branches:
        - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        submodules: true
    - name: Set up JDK 18
      uses: actions/setup-java@main
      with:
        java-version: 18
        distribution: temurin
    - name: Set up NDK r21e
      uses: nttld/setup-ndk@main
      id: setup-ndk
      with:
        ndk-version: r21e
    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@master
      with:
        version: 1.10.2
    - name: Build
      env:
        NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
      run: |
        ./build_libvpx_clang.sh
        ./build_ffmpeg_clang.sh
        ./patch_ffmpeg.sh
        ./patch_boringssl.sh
        ./build_boringssl.sh
    - name: Assemble APK
      run: ./gradlew --no-daemon assembleAfatRelease
