name: Java Ci

on:
  push:
    branches:
        - '**'
  pull_request:
    branches:
        - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        submodules: true
    - name: Install build dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y openjdk-11-jdk-headless ninja-build golang-go yasm
    - name: Set up NDK r21e
      uses: nttld/setup-ndk@main
      id: setup-ndk
      with:
        ndk-version: r21e
    - name: Build dependencies
      env:
        NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
      working-directory: TMessagesProj/jni
      run: |
        echo -e 'APP_ID = ${{ secrets.API_ID }}\nAPP_HASH = ${{ secrets.API_HASH }}' > API_KEYS
        ./build_libvpx_clang.sh
        ./build_ffmpeg_clang.sh
        ./patch_ffmpeg.sh
        ./patch_boringssl.sh
        ./build_boringssl.sh
    - name: Assemble APK
      run: ./gradlew --no-daemon assembleAfatRelease
